setwd("~/Desktop/phage_enrichment_fixed/")
source("functions/essentials.R")
setwd("~/Desktop/bac2food/3_magmapper")
# Prerequisites: install.packages(c("tidyverse"))
library(tidyverse)

print("Loading pre-calculated PCoA coordinates...")
# 1. Load the tiny coordinate file generated by Python
#Final NMDS Stress: 0.0864 goood
df <- read_csv("/data/bac2food/bac_food_binarymatrix/MultiSample_tSNE_Coordinates.csv", show_col_types = FALSE)
df<-df%>%rename(sampleID=Sample)
df<-add_metadata(df) %>% tibble()
df$genus<-sapply(df$MAG,function(s){strsplit(s,"_")[[1]][2]})
df$phylum<-sapply(df$genus,function(s)name2rank(s,"phylum"))
df$class<-sapply(df$genus,function(s)name2rank(s,"class"))
df$family<-sapply(df$genus,function(s)name2rank(s,"family"))

# Check if the columns are named NMDS1/2 or Dim1/2 depending on the Python script used
x_col <- if("NMDS1" %in% names(df)) "NMDS1" else if("Dim1" %in% names(df)) "Dim1" else "PC1"
y_col <- if("NMDS2" %in% names(df)) "NMDS2" else if("Dim2" %in% names(df)) "Dim2" else "PC2"

print("Generating high-resolution artifact-free plot...")
p <- ggplot(df, aes(x = .data[[x_col]], y = .data[[y_col]], color = family)) +
  geom_point(size = 3, alpha = 0.7) +
  theme_minimal() +
  scale_color_viridis_d(option = "turbo") + 
  labs(
    title = "Multi-Cohort Dietary Niches",
    subtitle = "Non-Linear Embedding of Dietary Capacities (1.7M foods)",
    # No more percentages! Just the dimension names.
    x = "NMDS 1",
    y = "NMDS 2",
    color = "Family"
  ) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    legend.position = "bottom",
    legend.text = element_text(size = 8),
    legend.title = element_text(face = "bold", size = 10),
    legend.key.size = unit(0.5, "cm")
  ) +
  guides(color=guide_legend(nrow=6,byrow=TRUE)) + facet_wrap(age~.)

print(p)

out_file <- "MultiSample_Dietary_Niche_Plot.png"
ggsave(out_file, plot = p, width = 16, height = 8, dpi = 300,bg = "white")

print(paste("DONE! Saved publication-ready figure to:", out_file))
